### PR TITLE
Use src layout and fix tests

### PR DESCRIPTION
**Pull request by danielfrg**
Fixes https://github.com/danielfrg/mkdocs-jupyter/issues/168

### CODE REVIEW

**Comment by xmnlab** [comment]
@danielfrg , sorry for writing into an old PR. 

I wonder if there was any specific reason for moving to python 3.9? https://github.com/danielfrg/mkdocs-jupyter/pull/169/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R5

I am asking that because with the version 0.24.3 (the latest one that supports python 3.8) the switch toggle is not working.

So I am trying to define a plan to fix this issue without increasing the lower bond for python.
although it is just for development (or just for creating the documentation, but it was not in the plans the creation of specific set of dependencies just for documentation.

any thoughts?

**Comment by danielfrg** [comment]
Mostly to reduce maintenance and becuase its getting to its EoL.

**Comment by xmnlab** [comment]
I see .. well it is a bit sad, because there is still a few months (2024-10) until its EoL and a lot of the projects still support it
thanks for the quick answer

**Comment by xmnlab** [comment]
PS: we are using mkdocs-jupyter in almost all our projects, including a project template (based on cookiecutter) that we are maintaining.

**Comment by danielfrg** [comment]
If you make a PR and tests pass on 3.8 I am happy to bring it back. Since I am using newer versions its not an issue for me at the moment.

**Comment by xmnlab** [comment]
thanks @danielfrg ! I will give it a try! appreciate that

**Pull request merged**
