### PR TITLE
Creating "Download Data" Functionality Per Page

### PR DESCRIPTION
**Pull request by jpjon**
Added a "Download Data" button optional for each page:
image

This functionality has been tested with the `mkdocs-jupyter/src/mkdocs_jupyter/tests/mkdocs/material-with-nbs.yml` file specified in the `CONTRIBUTING.md` doc.

To test this functionality, a new configuration has to be added to the `material-with-nbs.yml` file. 
image

Bulk of the functionality can be found in the `mkdocs-jupyter/src/mkdocs_jupyter/plugin.py` file, specifically in the `on_post_page` method.

### CODE REVIEW

**Comment by jpjon** [comment]
I'd also like your insights on how multiple data sources are downloadable. For example, with each data file, a new download icon appears, like so:
image

I can see this getting messy and was thinking of having .zip files be a suitable replacement instead. On the other hand, this might be annoying for users to have to unzip files for pages has multiple associated data sources. 

Love to hear your thoughts!

**Comment by danielfrg** [comment]
I think its fair to leave it as an option for the writers to decide if they want one or many downloads. So this lgtm.

**Comment by jpjon** [comment]
Deleted the test_files and commented out the `data_files` configurations for a hopefully easy fix past the tests.

**Comment by jpjon** [comment]
@danielfrg Am I expected to provide my own cloudfare secrets? I think that's the main issue with the 
`docs / cf-pages / prod` check. 

Specifically, the workflow error is:
```
cf-pages / prod
Secret CLOUDFLARE_ACCOUNT_ID is required, but not provided while calling.
```

**Comment by danielfrg** [comment]
No, thats fine. That fails on PR and I never disabled it

**Comment by danielfrg** [comment]
Thanks for the PR!

**Comment by jpjon** [comment]
Happy to contribute! Do you know when to expect the next update to be released on PyPI?

**Pull request merged**
