### PR TITLE
Set title of page based on first h1 element in ipynb document

### LINKED ISSUE #37: Making use of title from nbconvert
mkdocs-jupyter is currently not setting the title attribute in the mkdoc page object. Therefore, if no title is provided manually in the navigation, mkdocs uses the filename. 

When nbconvert converts a document it can generate a title (see e.g. the html files it creates). I'm not entirely sure how it determines the title, but it might be the first h1 header it sees I the file. It would be nice if mkdocs-jupyter could use the title from nbconvert to set the title in the mkdoc page object. 

I'm not sure how to implement this in a clean way.

### PR DESCRIPTION
**Pull request by hannorein**
Simple implementation which resolves #37.

### CODE REVIEW

**Comment by danielfrg** [comment]
Aha! very nice and easy way to solve it.

Thank you!

**Comment by hannorein** [comment]
Any chance you could push this to pypi? Then I wouldn't have to figure out how to use my own repository of your package on readthedocs. ;-) Thanks!

**Comment by danielfrg** [comment]
yes, i will push an update soon

**Comment by danielfrg** [comment]
Version `0.17.2` includes your PR

**Comment by hannorein** [comment]
Thank you! 🙏

**Comment by giswqs** [comment]
Is there a way to keep the old settings (i.e., set title of page based on the file name)? The new release renders all my notebooks without h1 element as None. I have more than 100 notebooks and I would prefer to use filename rather than h1. Thanks.  

https://geemap.org/notebooks/00_geemap_key_features/

image

**Pull request merged**
